# Generated by Django 5.1.15 on 2026-07-18 14:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("providers", "0002_seed_builtin_providers"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("capability", models.CharField(max_length=40)),
                ("resource_type", models.CharField(blank=True, max_length=80)),
                ("resource_key", models.CharField(blank=True, max_length=255)),
                ("correlation_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("success", "Succès"),
                            ("failed", "Échec"),
                            ("partial", "Partiel"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("records_received", models.PositiveIntegerField(default=0)),
                ("records_created", models.PositiveIntegerField(default=0)),
                ("records_updated", models.PositiveIntegerField(default=0)),
                ("conflicts_created", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_runs",
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SourceObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("entity_type", models.CharField(max_length=60)),
                ("external_id", models.CharField(max_length=255)),
                ("external_url", models.URLField(blank=True, max_length=600)),
                ("canonical_model", models.CharField(blank=True, max_length=100)),
                ("canonical_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("observed_at", models.DateTimeField()),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=1, max_digits=5),
                ),
                ("payload_version", models.CharField(default="1", max_length=40)),
                ("normalized_payload", models.JSONField(blank=True, default=dict)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_observations",
                        to="providers.provider",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="ingestion.ingestionrun",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="observations",
                        to="providers.providersnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("entity_type", models.CharField(max_length=60)),
                ("canonical_model", models.CharField(blank=True, max_length=100)),
                ("canonical_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("field_name", models.CharField(max_length=120)),
                ("current_value", models.JSONField(blank=True, default=dict)),
                ("incoming_value", models.JSONField(blank=True, default=dict)),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ouvert"),
                            ("resolved", "Résolu"),
                            ("ignored", "Ignoré"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "losing_observation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ingestion.sourceobservation",
                    ),
                ),
                (
                    "winning_observation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ingestion.sourceobservation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ingestionrun",
            index=models.Index(
                fields=["provider", "capability"], name="ingestion_i_provide_554a3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingestionrun",
            index=models.Index(fields=["status"], name="ingestion_i_status_735e16_idx"),
        ),
        migrations.AddIndex(
            model_name="ingestionrun",
            index=models.Index(
                fields=["correlation_id"], name="ingestion_i_correla_7526ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sourceobservation",
            index=models.Index(
                fields=["canonical_model", "canonical_id"],
                name="ingestion_s_canonic_e92932_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sourceobservation",
            index=models.Index(
                fields=["entity_type", "external_id"],
                name="ingestion_s_entity__d71cbc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataconflict",
            index=models.Index(
                fields=["entity_type", "field_name", "status"],
                name="ingestion_d_entity__24b9e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataconflict",
            index=models.Index(
                fields=["canonical_model", "canonical_id"],
                name="ingestion_d_canonic_e20aad_idx",
            ),
        ),
    ]
