# Generated by Django 4.2.29 on 2026-04-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('nationality', models.CharField(blank=True, max_length=3, verbose_name='Nationalité')),
                ('country_name', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('status', models.CharField(choices=[('WorldTeam', 'UCI WorldTeam'), ('ProTeam', 'UCI ProTeam'), ('Continental', 'Continental'), ('Women', "Women's Team"), ('National', 'Équipe Nationale')], default='Continental', max_length=20, verbose_name='Statut')),
                ('abbreviation', models.CharField(blank=True, max_length=10, verbose_name='Abréviation')),
                ('jersey_url', models.URLField(blank=True, verbose_name='URL maillot')),
                ('logo_url', models.URLField(blank=True, verbose_name='URL logo')),
                ('bike_brand', models.CharField(blank=True, max_length=100, verbose_name='Vélo')),
                ('clothing_brand', models.CharField(blank=True, max_length=100, verbose_name='Équipementier')),
                ('manager', models.CharField(blank=True, max_length=200, verbose_name='Directeur sportif')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('pcs_url', models.URLField(blank=True, verbose_name='URL PCS')),
                ('wins', models.IntegerField(default=0, verbose_name='Victoires')),
                ('points', models.FloatField(default=0, verbose_name='Points')),
                ('team_rank', models.IntegerField(blank=True, null=True, verbose_name='Classement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('rider', 'Coureur'), ('captain', 'Capitaine de route'), ('domestique', 'Équipier')], default='rider', max_length=20, verbose_name='Rôle')),
                ('joined_date', models.DateField(blank=True, null=True, verbose_name="Date d'arrivée")),
                ('left_date', models.DateField(blank=True, null=True, verbose_name='Date de départ')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_history', to='riders.rider', verbose_name='Coureur')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='teams.team', verbose_name='Équipe')),
            ],
            options={
                'verbose_name': 'Effectif',
                'verbose_name_plural': 'Effectifs',
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['slug', 'year'], name='teams_team_slug_f1ca2b_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['year'], name='teams_team_year_15e10c_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['status'], name='teams_team_status_d66a03_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['nationality'], name='teams_team_nationa_dced8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('slug', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='teamroster',
            unique_together={('team', 'rider')},
        ),
    ]
