# Generated by Django 4.2.29 on 2026-04-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('classification', models.CharField(blank=True, choices=[('1.UWT', '1.UWT - WorldTour 1 jour'), ('2.UWT', '2.UWT - WorldTour Étapes'), ('1.Pro', '1.Pro - ProSeries 1 jour'), ('2.Pro', '2.Pro - ProSeries Étapes'), ('1.1', '1.1 - Elite 1 jour'), ('2.1', '2.1 - Elite Étapes'), ('1.2', '1.2 - Nationale/Continentale 1 jour'), ('2.2', '2.2 - Nationale/Continentale Étapes'), ('CC', 'CC - Championnat Continental'), ('CN', 'CN - Championnat National'), ('WC', 'WC - Championnat du Monde'), ('OG', 'OG - Jeux Olympiques'), ('1.WWT', '1.WWT - Women WorldTour 1 jour'), ('2.WWT', '2.WWT - Women WorldTour Étapes')], max_length=10, verbose_name='Classification')),
                ('circuit', models.CharField(blank=True, choices=[('UCI World Tour', 'UCI World Tour'), ('UCI ProSeries', 'UCI ProSeries'), ('UCI Continental Circuit', 'UCI Continental Circuit'), ('UCI Europe Tour', 'UCI Europe Tour'), ('UCI America Tour', 'UCI America Tour'), ('UCI Asia Tour', 'UCI Asia Tour'), ('UCI Africa Tour', 'UCI Africa Tour'), ('UCI Oceania Tour', 'UCI Oceania Tour'), ('UCI Women WorldTour', 'UCI Women WorldTour'), ('National Championships', 'Championnats Nationaux'), ('World Championships', 'Championnats du Monde'), ('Olympic Games', 'Jeux Olympiques')], max_length=50, verbose_name='Circuit')),
                ('country', models.CharField(blank=True, max_length=3, verbose_name='Pays')),
                ('country_name', models.CharField(blank=True, max_length=100, verbose_name='Pays (nom)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de départ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distance (km)')),
                ('stages_count', models.IntegerField(default=1, verbose_name="Nombre d'étapes")),
                ('is_stage_race', models.BooleanField(default=False, verbose_name='Course par étapes')),
                ('is_monument', models.BooleanField(default=False, verbose_name='Monument')),
                ('is_grand_tour', models.BooleanField(default=False, verbose_name='Grand Tour')),
                ('edition', models.IntegerField(blank=True, null=True, verbose_name='Édition')),
                ('departure_city', models.CharField(blank=True, max_length=100, verbose_name='Ville de départ')),
                ('arrival_city', models.CharField(blank=True, max_length=100, verbose_name="Ville d'arrivée")),
                ('pcs_url', models.URLField(blank=True, verbose_name='URL PCS')),
                ('photo_url', models.URLField(blank=True, verbose_name='Photo URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Numéro')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nom')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('departure', models.CharField(blank=True, max_length=100, verbose_name='Départ')),
                ('arrival', models.CharField(blank=True, max_length=100, verbose_name='Arrivée')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distance (km)')),
                ('stage_type', models.CharField(choices=[('flat', 'Plat'), ('hilly', 'Vallonné'), ('mountain', 'Montagne'), ('mountain_finish', 'Arrivée en altitude'), ('tt', 'Contre-la-montre'), ('itt', 'Contre-la-montre individuel'), ('ttt', 'Contre-la-montre par équipes'), ('cobbles', 'Pavés'), ('prologue', 'Prologue')], default='flat', max_length=20, verbose_name="Type d'étape")),
                ('elevation_gain', models.IntegerField(blank=True, null=True, verbose_name='Dénivelé positif (m)')),
                ('pcs_url', models.URLField(blank=True, verbose_name='URL PCS')),
                ('profile_url', models.URLField(blank=True, verbose_name='URL profil')),
            ],
            options={
                'verbose_name': 'Étape',
                'verbose_name_plural': 'Étapes',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='StartList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib_number', models.IntegerField(blank=True, null=True, verbose_name='Dossard')),
                ('withdrew', models.BooleanField(default=False, verbose_name='Forfait')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_list', to='races.race', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Liste de départ',
                'verbose_name_plural': 'Listes de départ',
            },
        ),
    ]
