# Generated by Django 4.2.29 on 2026-04-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riders', '0001_initial'),
        ('teams', '0001_initial'),
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startlist',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_lists', to='riders.rider', verbose_name='Coureur'),
        ),
        migrations.AddField(
            model_name='startlist',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_lists', to='teams.team', verbose_name='Équipe'),
        ),
        migrations.AddField(
            model_name='stage',
            name='leader_after',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_led', to='riders.rider', verbose_name="Leader après l'étape"),
        ),
        migrations.AddField(
            model_name='stage',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='races.race', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='stage',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_wins_rel', to='riders.rider', verbose_name='Vainqueur'),
        ),
        migrations.AddField(
            model_name='stage',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_wins_rel', to='teams.team', verbose_name='Équipe vainqueur'),
        ),
        migrations.AddField(
            model_name='race',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_races', to='riders.rider', verbose_name='Vainqueur'),
        ),
        migrations.AddField(
            model_name='race',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_races', to='teams.team', verbose_name='Équipe vainqueur'),
        ),
        migrations.AlterUniqueTogether(
            name='startlist',
            unique_together={('race', 'rider')},
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['race', 'number'], name='races_stage_race_id_3e0330_idx'),
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['date'], name='races_stage_date_1f4712_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('race', 'number')},
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['slug', 'year'], name='races_race_slug_51e4ae_idx'),
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['year'], name='races_race_year_8d03e7_idx'),
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['classification'], name='races_race_classif_516bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['start_date'], name='races_race_start_d_cf3791_idx'),
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['is_grand_tour'], name='races_race_is_gran_c8989b_idx'),
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['is_monument'], name='races_race_is_monu_9252c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='race',
            unique_together={('slug', 'year')},
        ),
    ]
