# Generated by Django 4.2.29 on 2026-04-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='profile_url',
            field=models.URLField(blank=True, verbose_name='URL profil altimétrique'),
        ),
    ]
