version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: pcs_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pcs_prod
      POSTGRES_USER: pcs_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pcs_pgdata:/var/lib/postgresql/data
    networks:
      - pcs_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pcs_user -d pcs_prod"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    image: ${DOCKER_HUB_USERNAME}/cyclostats:latest
    container_name: pcs_web
    restart: unless-stopped
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=pcs_postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=pcs_prod
      - DB_USER=pcs_user
      - DB_PORT=5432
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - HOME=/tmp
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pcs_network
    ports:
      - "8800:8000"
    volumes:
      - static_volume:/app/staticfiles
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 --worker-tmp-dir /tmp pcs_project.wsgi:application"

networks:
  pcs_network:

volumes:
  pcs_pgdata:
  static_volume:
