# Generated by Django 4.2.29 on 2026-04-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=20, verbose_name='Type')),
                ('slug', models.CharField(blank=True, max_length=200, verbose_name='Slug')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Année')),
                ('success', models.BooleanField(default=True, verbose_name='Succès')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Log de synchronisation',
                'verbose_name_plural': 'Logs de synchronisation',
                'ordering': ['-created_at'],
            },
        ),
    ]
