# Generated by Django 5.1.15 on 2026-06-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=40, verbose_name='Type')),
                ('ref', models.CharField(blank=True, max_length=200, verbose_name='Référence')),
                ('status', models.CharField(choices=[('ok', 'Succès'), ('error', 'Erreur'), ('empty', 'Vide')], default='ok', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='Durée (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de synchronisation',
                'verbose_name_plural': 'Logs de synchronisation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', '-created_at'], name='core_synclo_entity__d25aaf_idx'), models.Index(fields=['status', '-created_at'], name='core_synclo_status_4817f7_idx')],
            },
        ),
    ]
