# Generated by Django 5.1.15 on 2026-07-18 15:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0002_seed_builtin_providers"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualProviderRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("capability", models.CharField(max_length=40)),
                ("resource_key", models.CharField(max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
                ("author", models.CharField(blank=True, max_length=150)),
                ("justification", models.TextField(blank=True)),
                ("old_value", models.JSONField(blank=True, default=dict)),
                ("new_value", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["capability", "resource_key"],
                "indexes": [
                    models.Index(
                        fields=["capability", "active"],
                        name="providers_m_capabil_3f63b2_idx",
                    ),
                    models.Index(
                        fields=["resource_key"], name="providers_m_resourc_3103e6_idx"
                    ),
                ],
            },
        ),
    ]
