from enum import StrEnum


class ProviderCapability(StrEnum):
    CALENDAR = 'CALENDAR'
    RACE_SERIES = 'RACE_SERIES'
    RACE_EDITIONS = 'RACE_EDITIONS'
    STAGES = 'STAGES'
    ROUTE = 'ROUTE'
    PROFILE = 'PROFILE'
    KEYPOINTS = 'KEYPOINTS'
    RIDERS = 'RIDERS'
    TEAMS = 'TEAMS'
    STARTLIST = 'STARTLIST'
    RESULTS = 'RESULTS'
    CLASSIFICATIONS = 'CLASSIFICATIONS'
    LIVE_STATE = 'LIVE_STATE'
    LIVE_GROUPS = 'LIVE_GROUPS'
    LIVE_EVENTS = 'LIVE_EVENTS'
    IMAGES = 'IMAGES'
