# Generated by Django 4.2.29 on 2026-04-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiderRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_type', models.CharField(choices=[('pcs', 'PCS Points'), ('uci', 'UCI Points'), ('uci_team', 'UCI Équipes'), ('wins', 'Victoires')], default='pcs', max_length=20, verbose_name='Type')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('rank', models.IntegerField(verbose_name='Position')),
                ('points', models.FloatField(default=0, verbose_name='Points')),
                ('previous_rank', models.IntegerField(blank=True, null=True, verbose_name='Position précédente')),
                ('nationality', models.CharField(blank=True, max_length=3, verbose_name='Nationalité')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Classement coureur',
                'verbose_name_plural': 'Classements coureurs',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='TeamRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_type', models.CharField(choices=[('pcs', 'PCS Points'), ('uci', 'UCI Points'), ('uci_team', 'UCI Équipes'), ('wins', 'Victoires')], default='uci_team', max_length=20, verbose_name='Type')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('rank', models.IntegerField(verbose_name='Position')),
                ('points', models.FloatField(default=0, verbose_name='Points')),
                ('previous_rank', models.IntegerField(blank=True, null=True, verbose_name='Position précédente')),
                ('wins', models.IntegerField(default=0, verbose_name='Victoires')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Classement équipe',
                'verbose_name_plural': 'Classements équipes',
                'ordering': ['rank'],
            },
        ),
    ]
