# Generated by Django 4.2.29 on 2026-04-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riders', '0001_initial'),
        ('rankings', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamranking',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='teams.team', verbose_name='Équipe'),
        ),
        migrations.AddField(
            model_name='riderranking',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='riders.rider', verbose_name='Coureur'),
        ),
        migrations.AddField(
            model_name='riderranking',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_rankings', to='teams.team', verbose_name='Équipe'),
        ),
        migrations.AddIndex(
            model_name='teamranking',
            index=models.Index(fields=['ranking_type', 'year', 'rank'], name='rankings_te_ranking_77330c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamranking',
            unique_together={('team', 'ranking_type', 'year')},
        ),
        migrations.AddIndex(
            model_name='riderranking',
            index=models.Index(fields=['ranking_type', 'year', 'rank'], name='rankings_ri_ranking_7aec0a_idx'),
        ),
        migrations.AddIndex(
            model_name='riderranking',
            index=models.Index(fields=['year'], name='rankings_ri_year_090132_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='riderranking',
            unique_together={('rider', 'ranking_type', 'year')},
        ),
    ]
