# Generated by Django 5.1.15 on 2026-06-20 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcs_live_id', models.IntegerField(blank=True, null=True)),
                ('race_status', models.CharField(choices=[('preview', 'Avant course'), ('racing', 'En course'), ('finished', 'Terminée'), ('unknown', 'Inconnu')], default='unknown', max_length=12)),
                ('km_done', models.FloatField(blank=True, null=True)),
                ('km_to_go', models.FloatField(blank=True, null=True)),
                ('max_km', models.FloatField(blank=True, null=True)),
                ('perc', models.FloatField(blank=True, null=True)),
                ('avg_speed', models.FloatField(blank=True, null=True)),
                ('min_ele', models.IntegerField(blank=True, null=True)),
                ('max_ele', models.IntegerField(blank=True, null=True)),
                ('started_ts', models.BigIntegerField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si vrai, le worker poll cette session.')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_session', to='catalog.stage')),
            ],
            options={
                'verbose_name': 'Session live',
                'verbose_name_plural': 'Sessions live',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('label', models.CharField(max_length=80)),
                ('gap', models.CharField(blank=True, max_length=20)),
                ('rider_count', models.IntegerField(blank=True, null=True)),
                ('riders', models.JSONField(blank=True, default=list)),
                ('km_point', models.FloatField(blank=True, null=True)),
                ('profile_pct', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='live.livesession')),
            ],
            options={
                'verbose_name': 'Groupe live',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqnr', models.IntegerField(blank=True, db_index=True, null=True)),
                ('marker', models.CharField(blank=True, max_length=40)),
                ('text', models.TextField(blank=True)),
                ('html', models.TextField(blank=True)),
                ('kind', models.CharField(blank=True, max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='live.livesession')),
            ],
            options={
                'verbose_name': 'Événement live',
                'ordering': ['-order', '-seqnr'],
                'unique_together': {('session', 'seqnr')},
            },
        ),
    ]
