# Generated by Django 5.1.15 on 2026-06-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='start_time',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
