# Generated by Django 5.1.15 on 2026-06-21 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_delete_jerseywearer'),
        ('live', '0002_livesession_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=600, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Abonnement push',
                'verbose_name_plural': 'Abonnements push',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AddField(
            model_name='livesession',
            name='last_notified_event_seq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livesession',
            name='notified_finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livesession',
            name='notified_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livesession',
            name='notified_start',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RaceFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='catalog.race')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='live.pushsubscription')),
            ],
            options={
                'verbose_name': 'Suivi de course',
                'verbose_name_plural': 'Suivis de course',
                'ordering': ['-created_at'],
                'unique_together': {('subscription', 'race')},
            },
        ),
    ]
