# Generated by Django 4.2.29 on 2026-04-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Position')),
                ('time', models.DurationField(blank=True, null=True, verbose_name='Temps')),
                ('time_gap', models.CharField(blank=True, max_length=20, verbose_name='Écart')),
                ('points', models.FloatField(default=0, verbose_name='Points')),
                ('uci_points', models.FloatField(default=0, verbose_name='Points UCI')),
                ('dnf', models.BooleanField(default=False, verbose_name='Abandon')),
                ('dns', models.BooleanField(default=False, verbose_name='Non partant')),
                ('dsq', models.BooleanField(default=False, verbose_name='Disqualifié')),
                ('is_stage', models.BooleanField(default=False, verbose_name="Résultat d'étape")),
                ('result_type', models.CharField(choices=[('gc', 'Classement Général'), ('stage', 'Étape'), ('points', 'Points'), ('kom', 'Montagne'), ('youth', 'Jeunes'), ('team', 'Équipes')], default='gc', max_length=20, verbose_name='Type de résultat')),
            ],
            options={
                'verbose_name': 'Résultat',
                'verbose_name_plural': 'Résultats',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('nationality', models.CharField(blank=True, choices=[('AFG', 'Afghanistan'), ('ALB', 'Albanie'), ('DZA', 'Algérie'), ('AND', 'Andorre'), ('ARG', 'Argentine'), ('ARM', 'Arménie'), ('AUS', 'Australie'), ('AUT', 'Autriche'), ('AZE', 'Azerbaïdjan'), ('BEL', 'Belgique'), ('BLR', 'Biélorussie'), ('BOL', 'Bolivie'), ('BRA', 'Brésil'), ('BGR', 'Bulgarie'), ('CMR', 'Cameroun'), ('CAN', 'Canada'), ('CHL', 'Chili'), ('CHN', 'Chine'), ('COL', 'Colombie'), ('CRI', 'Costa Rica'), ('HRV', 'Croatie'), ('CUB', 'Cuba'), ('CZE', 'République Tchèque'), ('DNK', 'Danemark'), ('ECU', 'Équateur'), ('EGY', 'Égypte'), ('ERI', 'Érythrée'), ('EST', 'Estonie'), ('ETH', 'Éthiopie'), ('FIN', 'Finlande'), ('FRA', 'France'), ('GBR', 'Grande-Bretagne'), ('GEO', 'Géorgie'), ('DEU', 'Allemagne'), ('GHA', 'Ghana'), ('GRC', 'Grèce'), ('GTM', 'Guatemala'), ('HUN', 'Hongrie'), ('ISL', 'Islande'), ('IND', 'Inde'), ('IRI', 'Iran'), ('IRL', 'Irlande'), ('ISR', 'Israël'), ('ITA', 'Italie'), ('JAM', 'Jamaïque'), ('JPN', 'Japon'), ('KAZ', 'Kazakhstan'), ('KEN', 'Kenya'), ('LAT', 'Lettonie'), ('LTU', 'Lituanie'), ('LUX', 'Luxembourg'), ('MEX', 'Mexique'), ('MDA', 'Moldavie'), ('MON', 'Monaco'), ('MAR', 'Maroc'), ('NLD', 'Pays-Bas'), ('NZL', 'Nouvelle-Zélande'), ('NOR', 'Norvège'), ('PAN', 'Panama'), ('PER', 'Pérou'), ('POL', 'Pologne'), ('PRT', 'Portugal'), ('ROU', 'Roumanie'), ('RUS', 'Russie'), ('RWA', 'Rwanda'), ('SAU', 'Arabie Saoudite'), ('SVK', 'Slovaquie'), ('SVN', 'Slovénie'), ('RSA', 'Afrique du Sud'), ('KOR', 'Corée du Sud'), ('ESP', 'Espagne'), ('SWE', 'Suède'), ('CHE', 'Suisse'), ('TPE', 'Taïwan'), ('TJK', 'Tadjikistan'), ('TUR', 'Turquie'), ('UKR', 'Ukraine'), ('USA', 'États-Unis'), ('URY', 'Uruguay'), ('UZB', 'Ouzbékistan'), ('VEN', 'Venezuela')], max_length=3, verbose_name='Nationalité')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Poids (kg)')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Taille (cm)')),
                ('specialty', models.CharField(blank=True, choices=[('climber', 'Grimpeur'), ('sprinter', 'Sprinteur'), ('time_trialist', 'Contre-la-montre'), ('rouleur', 'Rouleur'), ('puncheur', 'Puncheur'), ('all_rounder', 'Polyvalent'), ('classics', 'Spécialiste classiques'), ('domestique', 'Équipier')], max_length=20, verbose_name='Spécialité')),
                ('photo_url', models.URLField(blank=True, verbose_name='Photo URL')),
                ('pcs_url', models.URLField(blank=True, verbose_name='URL PCS')),
                ('uci_id', models.CharField(blank=True, max_length=100, verbose_name='ID UCI')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('pcs_points', models.IntegerField(default=0, verbose_name='Points PCS')),
                ('pcs_rank', models.IntegerField(blank=True, null=True, verbose_name='Classement PCS')),
                ('uci_points', models.FloatField(default=0, verbose_name='Points UCI')),
                ('uci_rank', models.IntegerField(blank=True, null=True, verbose_name='Classement UCI')),
                ('one_day_wins', models.IntegerField(default=0, verbose_name='Victoires 1 jour')),
                ('stage_wins', models.IntegerField(default=0, verbose_name="Victoires d'étapes")),
                ('gc_wins', models.IntegerField(default=0, verbose_name='Victoires GC')),
                ('grand_tour_wins', models.IntegerField(default=0, verbose_name='Grands Tours gagnés')),
                ('monument_wins', models.IntegerField(default=0, verbose_name='Monuments gagnés')),
                ('profile_score', models.IntegerField(default=0, verbose_name='Score profil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coureur',
                'verbose_name_plural': 'Coureurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RiderSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('points', models.FloatField(default=0, verbose_name='Points')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Classement')),
                ('wins', models.IntegerField(default=0, verbose_name='Victoires')),
                ('podiums', models.IntegerField(default=0, verbose_name='Podiums')),
                ('top10', models.IntegerField(default=0, verbose_name='Top 10')),
                ('races_ridden', models.IntegerField(default=0, verbose_name='Courses disputées')),
                ('days_in_race', models.IntegerField(default=0, verbose_name='Jours de course')),
                ('distance_raced', models.FloatField(default=0, verbose_name='Distance parcourue (km)')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='riders.rider', verbose_name='Coureur')),
            ],
            options={
                'verbose_name': 'Statistiques saisonnières',
                'verbose_name_plural': 'Statistiques saisonnières',
                'ordering': ['-year'],
            },
        ),
    ]
