# Generated by Django 4.2.29 on 2026-04-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riders', '0001_initial'),
        ('teams', '0001_initial'),
        ('races', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderseasonstats',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_season_stats', to='teams.team', verbose_name='Équipe'),
        ),
        migrations.AddField(
            model_name='rider',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_riders', to='teams.team', verbose_name='Équipe actuelle'),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='races.race', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='riders.rider', verbose_name='Coureur'),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_results', to='races.stage', verbose_name='Étape'),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_results', to='teams.team', verbose_name='Équipe'),
        ),
        migrations.AlterUniqueTogether(
            name='riderseasonstats',
            unique_together={('rider', 'year')},
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['slug'], name='riders_ride_slug_d8e212_idx'),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['nationality'], name='riders_ride_nationa_1a3cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['pcs_rank'], name='riders_ride_pcs_ran_c1d22e_idx'),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['specialty'], name='riders_ride_special_9dafa6_idx'),
        ),
        migrations.AddIndex(
            model_name='raceresult',
            index=models.Index(fields=['rider', 'year'], name='riders_race_rider_i_d807f6_idx'),
        ),
        migrations.AddIndex(
            model_name='raceresult',
            index=models.Index(fields=['race', 'stage'], name='riders_race_race_id_77bf06_idx'),
        ),
        migrations.AddIndex(
            model_name='raceresult',
            index=models.Index(fields=['rank'], name='riders_race_rank_74c1cf_idx'),
        ),
    ]
