# Generated by Django 5.1.15 on 2026-06-20 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('pcs_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(blank=True, max_length=3)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True)),
                ('specialties', models.JSONField(blank=True, default=dict)),
                ('detail_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coureur',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('year', models.IntegerField()),
                ('pcs_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('classification', models.CharField(blank=True, choices=[('1.UWT', '1.UWT'), ('2.UWT', '2.UWT'), ('1.Pro', '1.Pro'), ('2.Pro', '2.Pro'), ('1.1', '1.1'), ('2.1', '2.1'), ('1.2', '1.2'), ('2.2', '2.2'), ('1.WWT', '1.WWT'), ('2.WWT', '2.WWT'), ('CC', 'Championnat continental'), ('NC', 'Championnat national'), ('WC', 'Championnat du monde'), ('OG', 'Jeux olympiques')], max_length=10)),
                ('category', models.CharField(choices=[('ME', 'Hommes Élite'), ('WE', 'Femmes Élite'), ('MU', 'Hommes U23'), ('WU', 'Femmes U23'), ('MJ', 'Hommes Juniors'), ('WJ', 'Femmes Juniors')], default='ME', max_length=2)),
                ('circuit', models.CharField(blank=True, max_length=60)),
                ('country', models.CharField(blank=True, max_length=3)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('is_stage_race', models.BooleanField(default=False)),
                ('is_grand_tour', models.BooleanField(default=False)),
                ('is_monument', models.BooleanField(default=False)),
                ('edition', models.IntegerField(blank=True, null=True)),
                ('detail_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_races', to='catalog.rider')),
            ],
            options={
                'verbose_name': 'Course',
                'ordering': ['start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('departure', models.CharField(blank=True, max_length=120)),
                ('arrival', models.CharField(blank=True, max_length=120)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('stage_type', models.CharField(choices=[('flat', 'Plat'), ('hills_flat', 'Vallonné (arrivée plate)'), ('hills_uphill', 'Vallonné (arrivée en bosse)'), ('mountains_flat', 'Montagne (arrivée plate)'), ('mountains_uphill', 'Montagne (arrivée au sommet)'), ('itt', 'Contre-la-montre individuel'), ('ttt', 'Contre-la-montre par équipes'), ('prologue', 'Prologue'), ('unknown', 'Inconnu')], default='unknown', max_length=20)),
                ('profile_score', models.IntegerField(blank=True, null=True)),
                ('vertical_meters', models.IntegerField(blank=True, null=True)),
                ('gradient_final', models.FloatField(blank=True, null=True)),
                ('profile_image_url', models.URLField(blank=True)),
                ('elevation_points', models.JSONField(blank=True, default=list)),
                ('detail_synced_at', models.DateTimeField(blank=True, null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='catalog.race')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_wins', to='catalog.rider')),
            ],
            options={
                'verbose_name': 'Étape',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Climb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('km', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('avg_grad', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=10)),
                ('kind', models.CharField(choices=[('climb', 'Col'), ('sprint', 'Sprint')], default='climb', max_length=10)),
                ('location_url', models.CharField(blank=True, max_length=200)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='catalog.stage')),
            ],
            options={
                'verbose_name': 'Point clé',
                'ordering': ['km'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('year', models.IntegerField()),
                ('pcs_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(blank=True, max_length=3)),
                ('level', models.CharField(blank=True, max_length=40)),
                ('abbreviation', models.CharField(blank=True, max_length=10)),
                ('jersey_url', models.URLField(blank=True)),
                ('detail_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Équipe',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug', 'year'], name='catalog_tea_slug_bdbbb9_idx'), models.Index(fields=['year'], name='catalog_tea_year_0fcbe3_idx')],
                'unique_together': {('slug', 'year')},
            },
        ),
        migrations.AddField(
            model_name='stage',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_wins', to='catalog.team'),
        ),
        migrations.AddField(
            model_name='rider',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_riders', to='catalog.team'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('stage', 'Étape'), ('gc', 'Général'), ('points', 'Points'), ('kom', 'Montagne'), ('youth', 'Jeunes'), ('teams', 'Équipes')], default='stage', max_length=10)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('time', models.DurationField(blank=True, null=True)),
                ('time_gap', models.CharField(blank=True, max_length=30)),
                ('bonus', models.CharField(blank=True, max_length=20)),
                ('points_uci', models.IntegerField(blank=True, null=True)),
                ('points_pcs', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'Classé'), ('dnf', 'Abandon'), ('dns', 'Non partant'), ('otl', 'Hors délai'), ('dsq', 'Disqualifié')], default='ok', max_length=10)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='catalog.race')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='catalog.rider')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='catalog.stage')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='catalog.team')),
            ],
            options={
                'verbose_name': 'Résultat',
                'ordering': ['classification', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pcs', 'PCS'), ('uci', 'UCI'), ('team', 'Équipes')], max_length=10)),
                ('year', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('previous_rank', models.IntegerField(blank=True, null=True)),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='catalog.rider')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='catalog.team')),
            ],
            options={
                'verbose_name': 'Classement',
                'ordering': ['kind', 'rank'],
            },
        ),
        migrations.AddField(
            model_name='race',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_races', to='catalog.team'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='catalog.rider')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='catalog.team')),
            ],
            options={
                'verbose_name': 'Appartenance',
            },
        ),
        migrations.CreateModel(
            name='JerseyWearer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('stage', 'Étape'), ('gc', 'Général'), ('points', 'Points'), ('kom', 'Montagne'), ('youth', 'Jeunes'), ('teams', 'Équipes')], max_length=10)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jerseys_worn', to='catalog.rider')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jerseys', to='catalog.stage')),
            ],
            options={
                'verbose_name': 'Porteur de maillot',
                'unique_together': {('stage', 'classification')},
            },
        ),
        migrations.CreateModel(
            name='StartListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'Classé'), ('dnf', 'Abandon'), ('dns', 'Non partant'), ('otl', 'Hors délai'), ('dsq', 'Disqualifié')], default='ok', max_length=10)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startlist', to='catalog.race')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startlist_entries', to='catalog.rider')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startlist_entries', to='catalog.team')),
            ],
            options={
                'verbose_name': 'Engagé',
                'indexes': [models.Index(fields=['race'], name='catalog_sta_race_id_f000ca_idx'), models.Index(fields=['rider'], name='catalog_sta_rider_i_227f2e_idx')],
                'unique_together': {('race', 'rider')},
            },
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['race', 'number'], name='catalog_sta_race_id_0dece7_idx'),
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['date'], name='catalog_sta_date_e10b5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('race', 'number')},
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['race', 'stage', 'classification', 'rank'], name='catalog_res_race_id_2f2cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['rider'], name='catalog_res_rider_i_232bf1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('race', 'stage', 'rider', 'classification')},
        ),
        migrations.AddIndex(
            model_name='ranking',
            index=models.Index(fields=['kind', 'year', 'rank'], name='catalog_ran_kind_96cdfe_idx'),
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['slug', 'year'], name='catalog_rac_slug_fabdaa_idx'),
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['year'], name='catalog_rac_year_ec6684_idx'),
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['start_date'], name='catalog_rac_start_d_1dd87b_idx'),
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['classification'], name='catalog_rac_classif_a3d157_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='race',
            unique_together={('slug', 'year')},
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['rider', 'year'], name='catalog_mem_rider_i_59ade7_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['team', 'year'], name='catalog_mem_team_id_b7bfbe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('team', 'rider', 'year')},
        ),
    ]
