# Generated by Django 5.1.15 on 2026-06-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='finish_image_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='stage',
            name='map_image_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='stage',
            name='max_elevation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='min_elevation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
