# Generated by Django 5.1.15 on 2026-06-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_stage_finish_image_url_stage_map_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='gender',
            field=models.CharField(default='me', max_length=2),
        ),
    ]
