# Generated by Django 5.1.15 on 2026-06-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_ranking_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='profile_from_image',
            field=models.BooleanField(default=False),
        ),
    ]
