# Generated by Django 5.1.15 on 2026-06-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_stage_profile_from_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JerseyWearer',
        ),
    ]
