# Generated by Django 5.1.15 on 2026-07-18 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_delete_jerseywearer"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("canonical_slug", models.SlugField(max_length=220, unique=True)),
                ("current_name", models.CharField(max_length=220)),
                ("primary_country", models.CharField(blank=True, max_length=3)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Identité d'équipe",
                "verbose_name_plural": "Identités d'équipe",
                "ordering": ["current_name"],
            },
        ),
        migrations.AddField(
            model_name="race",
            name="finish_location",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="race",
            name="host_country",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="race",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="race",
            name="official_name",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="race",
            name="public_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="race",
            name="start_location",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="race",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Planifiée"),
                    ("active", "Active"),
                    ("finished", "Terminée"),
                    ("cancelled", "Annulée"),
                    ("unknown", "Inconnu"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="bonus_seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="result",
            name="elapsed_time_ms",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="result",
            name="gap_laps",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="result",
            name="gap_ms",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="result",
            name="penalty_seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="result",
            name="public_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="result",
            name="raw_display_time",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="rider",
            name="canonical_slug",
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="rider",
            name="gender_category",
            field=models.CharField(
                choices=[
                    ("ME", "Hommes Élite"),
                    ("WE", "Femmes Élite"),
                    ("MU", "Hommes U23"),
                    ("WU", "Femmes U23"),
                    ("MJ", "Hommes Juniors"),
                    ("WJ", "Femmes Juniors"),
                ],
                default="ME",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="rider",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="rider",
            name="normalized_name",
            field=models.CharField(blank=True, db_index=True, max_length=220),
        ),
        migrations.AddField(
            model_name="rider",
            name="public_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="stage",
            name="display_label",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="stage",
            name="profile_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="stage",
            name="public_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="stage",
            name="route_geometry",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="stage",
            name="sequence",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="stage",
            name="stage_key",
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name="stage",
            name="stage_kind",
            field=models.CharField(
                choices=[
                    ("road", "Route"),
                    ("itt", "Contre-la-montre individuel"),
                    ("ttt", "Contre-la-montre par équipes"),
                    ("prologue", "Prologue"),
                    ("split_stage", "Demi-étape"),
                ],
                default="road",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="startlistentry",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="startlistentry",
            name="public_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="startlistentry",
            name="role",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="startlistentry",
            name="source_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="startlistentry",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="startlist",
                to="catalog.stage",
            ),
        ),
        migrations.AddField(
            model_name="startlistentry",
            name="withdrawn_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="public_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.CreateModel(
            name="RaceSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("canonical_slug", models.SlugField(max_length=220, unique=True)),
                ("current_name", models.CharField(max_length=220)),
                (
                    "gender_category",
                    models.CharField(
                        choices=[
                            ("ME", "Hommes Élite"),
                            ("WE", "Femmes Élite"),
                            ("MU", "Hommes U23"),
                            ("WU", "Femmes U23"),
                            ("MJ", "Hommes Juniors"),
                            ("WJ", "Femmes Juniors"),
                        ],
                        default="ME",
                        max_length=2,
                    ),
                ),
                (
                    "discipline",
                    models.CharField(
                        choices=[("road", "Route")], default="road", max_length=20
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("one_day", "Course d'un jour"),
                            ("stage_race", "Course par étapes"),
                            ("championship_road_race", "Championnat route"),
                            ("championship_itt", "Championnat contre-la-montre"),
                        ],
                        default="one_day",
                        max_length=40,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("regular", "Régulier"),
                            ("world_championship", "Championnat du monde"),
                            ("continental_championship", "Championnat continental"),
                            ("national_championship", "Championnat national"),
                            ("olympic", "Jeux olympiques"),
                        ],
                        default="regular",
                        max_length=40,
                    ),
                ),
                ("primary_country", models.CharField(blank=True, max_length=3)),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("P0", "P0"),
                            ("P1", "P1"),
                            ("P2", "P2"),
                            ("P3", "P3"),
                        ],
                        default="P3",
                        max_length=2,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Série de course",
                "verbose_name_plural": "Séries de courses",
                "ordering": ["current_name"],
                "indexes": [
                    models.Index(
                        fields=["gender_category", "discipline"],
                        name="catalog_rac_gender__515346_idx",
                    ),
                    models.Index(fields=["scope"], name="catalog_rac_scope_31ef40_idx"),
                    models.Index(
                        fields=["importance"], name="catalog_rac_importa_b4617c_idx"
                    ),
                    models.Index(
                        fields=["active"], name="catalog_rac_active_fd701e_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="race",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="editions",
                to="catalog.raceseries",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seasons",
                to="catalog.teamidentity",
            ),
        ),
        migrations.CreateModel(
            name="RaceSeriesAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=220)),
                ("normalized_name", models.CharField(db_index=True, max_length=220)),
                ("valid_from_year", models.IntegerField(blank=True, null=True)),
                ("valid_to_year", models.IntegerField(blank=True, null=True)),
                ("locale", models.CharField(default="und", max_length=12)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series_aliases",
                        to="catalog.raceseries",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alias de série",
                "verbose_name_plural": "Alias de séries",
                "indexes": [
                    models.Index(
                        fields=["normalized_name"],
                        name="catalog_rac_normali_db3d48_idx",
                    )
                ],
                "unique_together": {
                    (
                        "series",
                        "normalized_name",
                        "valid_from_year",
                        "valid_to_year",
                        "locale",
                    )
                },
            },
        ),
    ]
