# Generated by Django 4.2.30 on 2026-05-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("year", models.IntegerField()),
                ("classification", models.CharField(blank=True, max_length=10)),
                ("circuit", models.CharField(blank=True, max_length=50)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("stages_count", models.IntegerField(default=1)),
                ("is_stage_race", models.BooleanField(default=False)),
                ("is_grand_tour", models.BooleanField(default=False)),
                ("is_monument", models.BooleanField(default=False)),
                ("country", models.CharField(blank=True, max_length=3)),
                ("country_name", models.CharField(blank=True, max_length=100)),
                ("distance", models.FloatField(blank=True, null=True)),
                ("departure_city", models.CharField(blank=True, max_length=100)),
                ("arrival_city", models.CharField(blank=True, max_length=100)),
                ("profile_url", models.URLField(blank=True)),
                ("pcs_url", models.URLField(blank=True)),
                ("last_fetched", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("nationality", models.CharField(blank=True, max_length=3)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("climber", "Climber"),
                            ("sprinter", "Sprinter"),
                            ("tt", "Time Trialist"),
                            ("rouleur", "Rouleur"),
                            ("puncheur", "Puncheur"),
                            ("all_rounder", "All-Rounder"),
                            ("classics", "Classics Specialist"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("pcs_rank", models.IntegerField(blank=True, null=True)),
                ("pcs_points", models.IntegerField(default=0)),
                ("uci_rank", models.IntegerField(blank=True, null=True)),
                ("uci_points", models.FloatField(default=0)),
                ("photo_url", models.URLField(blank=True)),
                ("pcs_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("year", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WorldTeam", "WorldTeam"),
                            ("ProTeam", "ProTeam"),
                            ("Continental", "Continental"),
                            ("Women", "Women"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nationality", models.CharField(blank=True, max_length=3)),
                ("pcs_url", models.URLField(blank=True)),
            ],
            options={"unique_together": {("slug", "year")},},
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("date", models.DateField(blank=True, null=True)),
                ("departure", models.CharField(blank=True, max_length=100)),
                ("arrival", models.CharField(blank=True, max_length=100)),
                ("distance", models.FloatField(blank=True, null=True)),
                (
                    "stage_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat"),
                            ("hilly", "Hilly"),
                            ("mountain", "Mountain"),
                            ("mountain_finish", "Mountain Finish"),
                            ("tt", "Time Trial"),
                            ("ttt", "Team Time Trial"),
                            ("itt", "Individual Time Trial"),
                            ("cobbles", "Cobbles"),
                            ("prologue", "Prologue"),
                        ],
                        default="flat",
                        max_length=20,
                    ),
                ),
                ("elevation_gain", models.IntegerField(blank=True, null=True)),
                ("profile_url", models.URLField(blank=True)),
                ("pcs_url", models.URLField(blank=True)),
                (
                    "leader_after",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stages_led",
                        to="cycling.rider",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="cycling.race",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stage_wins",
                        to="cycling.rider",
                    ),
                ),
                (
                    "winner_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stage_wins",
                        to="cycling.team",
                    ),
                ),
            ],
            options={"ordering": ["number"], "unique_together": {("race", "number")},},
        ),
        migrations.AddField(
            model_name="rider",
            name="current_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="riders",
                to="cycling.team",
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_races",
                to="cycling.rider",
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="winner_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_races",
                to="cycling.team",
            ),
        ),
        migrations.CreateModel(
            name="StartEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bib_number", models.IntegerField(blank=True, null=True)),
                ("withdrew", models.BooleanField(default=False)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="start_list",
                        to="cycling.race",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="start_entries",
                        to="cycling.rider",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="start_entries",
                        to="cycling.team",
                    ),
                ),
            ],
            options={"unique_together": {("race", "rider")},},
        ),
        migrations.CreateModel(
            name="RaceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("gc", "General Classification"),
                            ("stage", "Stage"),
                            ("points", "Points Classification"),
                            ("kom", "King of the Mountains"),
                            ("youth", "Youth Classification"),
                            ("team", "Team Classification"),
                        ],
                        default="gc",
                        max_length=10,
                    ),
                ),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("time_gap", models.CharField(blank=True, max_length=20)),
                ("points", models.FloatField(default=0)),
                ("uci_points", models.FloatField(default=0)),
                ("dnf", models.BooleanField(default=False)),
                ("dns", models.BooleanField(default=False)),
                ("dsq", models.BooleanField(default=False)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="cycling.race",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="cycling.rider",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="cycling.stage",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="cycling.team",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
                "indexes": [
                    models.Index(
                        fields=["race", "stage"], name="cycling_rac_race_id_902a14_idx"
                    ),
                    models.Index(
                        fields=["rider", "year"], name="cycling_rac_rider_i_af47d0_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="race",
            index=models.Index(
                fields=["slug", "year"], name="cycling_rac_slug_7e072c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="race",
            index=models.Index(
                fields=["start_date"], name="cycling_rac_start_d_0e80d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="race",
            index=models.Index(
                fields=["is_grand_tour"], name="cycling_rac_is_gran_d894e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="race",
            index=models.Index(
                fields=["is_monument"], name="cycling_rac_is_monu_f1f024_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="race", unique_together={("slug", "year")},
        ),
    ]
